# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=me.tnoctua
archives_base_name=soulcomponent

# Dependencies
fabric_version=0.128.1+1.21.5
nmodutils_version=1.0.0-beta.2

# Runtime Mods
modmenu_version=14.0.0-rc.2
sodium_version=0.6.13
sodium_extra_version=0.6.3
reese_sodium_version=1.8.3
no_chat_reports_version=2.12.0