# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w32a
yarn_mappings=25w32a+build.2
loader_version=0.17.0
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.1.0-beta.1
maven_group=me.tnoctua
archives_base_name=soulcomponent

# Dependencies
fabric_version=0.131.2+1.21.9
nmodutils_version=1.0.0-beta.2+mc1.21.5